### PR TITLE
Update .nf-core.yml

### PR DESCRIPTION
**Pull request by daisymut**
.nf-core.yml prevented the automated PR for the template update

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/sammyseq/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/sammyseq _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by mirpedrol — COMMENTED** [review]
You can continue skipping the `report_comment` linting step, but `multiqc_config` should be a list:
```
lint:
  multiqc_config:
    - report_comment
```

**Comment by mirpedrol** [comment]
Also, linting will fail because it is expecting the updates form the last template version, so don't worry for this PR, they can be ignored 🙂 let's just fix the `.nf-core.yml` and afterwards you can do the template update to fix the rest

**Comment by daisymut** [comment]
I didn't get what is the problem in the file preventing the creation of the template update PR, is it ok now?

**Review by mirpedrol — APPROVED** [review]
looks good now, thanks for the fix 🙂

**Comment by daisymut** [comment]
@mirpedrol can you please help me in fixing or skipping the linting error and merge? I can't find which file triggers the error message 

> ERROR: Invalid requirement: 'nf-core==': Expected end or semicolon (after name and no valid version specifier)
    nf-core==
           ^
Error: Process completed with exit code 1.

**Comment by mirpedrol** [comment]
This error will be fixed with the template update 3.0.2. I would advice to merge this PR with failing test and do the template update in a different PR, to simplify things. 
For the template update you can install the last version of nf-core/tools 3.0.2 and run [`nf-core pipelines syn`](https://nf-co.re/docs/nf-core-tools/pipelines/sync)
Alternatively you can also execute [the GitHub Action we have](https://github.com/nf-core/tools/actions/workflows/sync.yml) with the `Run workflow` button and making sure to write your pipeline name in the textbox (replacing "all")

**Comment by daisymut** [comment]
@mirpedrol thank you, I probably don't have the privileges to merge this PR with a failing required check :( the Merge button is still inactive despite your approval. Can you please force it?

**Comment by mirpedrol** [comment]
Done, you can now do the template update, thanks for this fix!

**Comment by daisymut** [comment]
Thank you for your help!

**Pull request merged**
